# Churn Modeling using **Artificial** Neural Network

The bank has been seeing unusual churn rates.So churn is when people leave the company and they've seen customers leaving at unusually high rates and they want to understand what the problem is and they want to assess and address that problem

Build a model which people are more likely to be reliable and which people are more likely to default

And that could govern the bank's decision on whether or not to give loans. This could be in terms of fradulent transactions.


and not even in a bank, in a different fianncial institution ,so you could find out which transactions are more likely to be fradulent which are less likely.

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
#for version
tf.__version__

'2.12.0'

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values


In [ ]:
#print matrix of features X
print(X)

In [ ]:
#print dependent variable
print(Y)

[1 0 1 ... 1 1 0]


## Part 1 - Data Preprocessing

### Importing the dataset

### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])


In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state=0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
#sequence of layers : input layers, hidden layers
ann = tf.keras.models.Sequential()#from keras library in tensorflow

### Adding the input layer and the first hidden layer

In [ ]:
#dense layer:for fully connected leyers

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))#units are no.of neurons


### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))#rectifier activationn function

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))#sigmoid gives the probability that the customer leaves the bank

## Part 3 - Training the ANN

***Compiling the ANN (with an optimizer and loss function and also metric=accuracy)***

In [ ]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'] )#here output is in binary so for binary to compute loss function binary_cross_entropy is used.For non binary classification : categorical_cross_entropy is used
#adamoptimizer : it updates the weights through stochastic gradient descent  in order to reduce the loss error between predictions and real results
#loss : is the way to compute difference between predictions and real results
#metrics for accuracy

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

#metrics features of training set, y train for the dependent variable of teh training set
#batch learning is always more efficient and more performant when training an artificial neural network
#epochs: how many times the model is trainined through the dataset


Epoch 1/100
250/250 [==============================] - 3s 3ms/step - loss: 0.8077 - accuracy: 0.3557
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6195 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5831 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5572 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5388 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5262 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5178 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5107 - accuracy: 0.7960
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5005 - accuracy: 0.7960
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4888 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
#it should be in 2D
#false for customer wont leave the bank
#true for customer leave the bank


1/1 [==============================] - 0s 51ms/step
[[ True]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
#convert the datatypes to float
X_test = X_test.astype(np.float32)
y_test = y_test.astype(np.float32)

# Assuming you've loaded the trained model 'ann'
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5).astype(np.float32)

63/63 [==============================] - 0s 2ms/step


In [ ]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 1.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1595    0]
 [ 405    0]]


0.7975

In [ ]:
#86 weere correctly predicted
#1595 correct predictions to customers stays in the bank
#0 correct predictions to customer leaves the bank
#0 incorrect predictions to customer leaves the bank
#202 incorrect predictions to customer stays in  the bank
